[platformio]
src_dir = Cntrl_V2

[env:genericSTM32F405RG]
platform = ststm32 @ 17.4.0

board = genericSTM32F405RG
framework = arduino

upload_protocol = stlink
debug_tool = stlink

lib_deps =
    robtillaart/AS5600 @ 0.4.1
    pazi88/STM32_CAN @ 1.1.0
    khoih-prog/STM32_TimerInterrupt @ 1.3.0
    stm32duino/STM32duino RTC @ 1.6.0

build_flags =
    -D NO_HW_SERIAL
    -D HAL_UART_MODULE_DISABLED
    -D ARDUINO_GENERIC_F405RGTX